name: Build
on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    env:
      GH_TOKEN: ${{ secrets.token }}
    runs-on: ubuntu-latest
    steps:
        - name: Check out repository code
          uses: actions/checkout@v3
        
        - name: Setup node
          uses: actions/setup-node@v3
          with:
            cache-dependency-path: angular/package-lock.json

# Installing dependencies
        - name: Installing dependencies
          run: cd ${{ github.workspace }}/angular && npm install

# Run tests          
#         - name: test
#           id: test
#           run: cd ${{ github.workspace }}/angular && npm run test
          
#         - name: Pass or fail
#           run: |
#             if: [[ ${{ steps.test.conclusion }} == 'failure' ]]; then exit 1; else exit 0; fi
            
# Build app
        - name: build app
          run: cd ${{ github.workspace }}/angular && npm run build

# Build docker image
        - name: docker image build
          run: docker build -t ghcr.io/awameg/nginx-angular:latest -t ghcr.io/awameg/nginx-angular:${GITHUB_SHA::8} .
        
        - name: docker login
          run: docker login ghcr.io -u $GITHUB_ACTOR -p ${{secrets.GITHUB_TOKEN}}
          
        - name: Publish docker image
          run: docker push ghcr.io/awameg/nginx-angular:latest && docker push ghcr.io/awameg/nginx-angular:${GITHUB_SHA::8}

# Get execution time for notification
        - name: get time
          id: get-time
          run: echo "::set-output name=time::$(gh run list --workflow build.yml | head -n 1 | awk -F'\t' '{print $8}')"     

# Notifications
        - name: Send mail success
          if: success()
          uses: dawidd6/action-send-mail@v2
          with:
            server_address: smtp.yandex.ru
            server_port: 465
            username: ${{ secrets.EMAIL_NOTIFY }}
            password: ${{ secrets.EMAIL_PASSWORD }}
            subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
            body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}. Execution time ${{ steps.get-time.outputs.time }}
            to: ${{ github.actor }}@yandex.ru
            from: GitHub ${{ github.repository }}
            
        - name: Send mail failure
          if: failure()
          uses: dawidd6/action-send-mail@v2
          with:
            server_address: smtp.yandex.ru
            server_port: 465
            username: ${{ secrets.EMAIL_NOTIFY }}
            password: ${{ secrets.EMAIL_PASSWORD }}
            subject: ${{ github.job }} job of ${{ github.repository }} has FAILED!!!
            body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has FAILED!!!
            to: ${{ github.actor }}@yandex.ru
            from: GitHub ${{ github.repository }}
