name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Check out repository code
          uses: actions/checkout@v3
        - run: cd ${{ github.workspace }}/angular && ls ./
        
        - name: Setup node
          uses: actions/setup-node@v3
          with:
            node-version: 16.13.x
            cache: 'npm'
            cache-dependency-path: angular/package-lock.json

# name: Build

# on:
#  pull_request:
#    branches:
#      - '*'
 
#  push:
#    branches:
#      - 'master'

# jobs:
#   build:
#     runs-on: ubuntu-18.04
#     steps:

#       - name: Setup node
#         uses: actions/setup-node@v3
#         with:
#           node-version: 16.13.x
#           cache: npm
#       - run: ls -la
        
      
#       - name: Installing dependencies
#         run: cd ./angular && npm install

#       - name: test
#         run: npm run test

#       - name: build app
#         run: npm run build
