name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Check out repository code
          uses: actions/checkout@v3
        - run: cd ${{ github.workspace }}/angular && ls ./
        
        - name: Setup node
          uses: actions/setup-node@v3
          with:
            node-version: 16.13.x
#             cache: 'npm'
            cache-dependency-path: angular/package-lock.json
        
        - name: Installing dependencies
          run: cd ${{ github.workspace }}/angular && npm install
          
#         - name: test
#           run: cd ${{ github.workspace }}/angular && npm run test

        - name: build app
          run: cd ${{ github.workspace }}/angular && npm run build
