name: test
env:
  GH_TOKEN: ${{ secrets.token }}

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Check out repository code
          uses: actions/checkout@v3
        - run: sleep 5
          
# Notifications
  notif:
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
        - name: Check out repository code
          uses: actions/checkout@v3
# Get email from git log
        - name: get email
          id: get-email
          run: echo "::set-output name=email::$(git log -n 1 --pretty=format:%ae)"
# Get execution time from api        
        - name: get time
          id: get-time
          run: echo "::set-output name=time::$(gh run list --workflow build.yml | head -n 1)"
# Send notification      
        - name: Send mail success
          if: success()
          uses: dawidd6/action-send-mail@v2
          with:
            server_address: smtp.yandex.ru
            server_port: 465
            username: ${{ secrets.EMAIL_NOTIFY }}
            password: ${{ secrets.EMAIL_PASSWORD }}
            subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
            body: "${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }} ${{ steps.get-time.outputs.time }}"
            to: ${{ steps.get-email.outputs.email }}
            from: GitHub ${{ github.repository }}
            
