name: Build

on:
 pull_request:
   branches:
     - '*'
 
 push:
   branches:
     - 'master'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: npm
      
      - name: Installing dependencies
        run: pwd
#         run: cd ./angular && npm install

#       - name: test
#         run: npm run test

#       - name: build app
#         run: npm run build
