name: test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.token }}
    steps:
        - name: Check out repository code
          uses: actions/checkout@v3
        
#         - name: Setup node
#           uses: actions/setup-node@v3
#           with:
#             node-version: 16.13.x
# #             cache: 'npm'
#             cache-dependency-path: angular/package-lock.json
#         - run: 'curl -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.token }}" https://api.github.com/user/emails'
        - run: |
            gh api \
            --method PATCH \
            -H "Accept: application/vnd.github+json" \
            /user/email/visibility \
            -f visibility='private'
# Notifications
#         - name: Send mail success
#           if: always()
#           uses: dawidd6/action-send-mail@v2
#           with:
#             server_address: smtp.yandex.ru
#             server_port: 465
#             username: ${{ secrets.EMAIL_NOTIFY }}
#             password: ${{ secrets.EMAIL_PASSWORD }}
#             subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
#             body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
#             to: ${{ github.actor }}@users.noreply.github.com
#             from: GitHub ${{ github.repository }}
            
